name: resposif_theme
description: "A new Flutter project."
publish_to: 'none' # Hapus baris ini jika Anda ingin mempublikasikan ke pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Menambahkan ikon Cupertino untuk aplikasi iOS
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Menambahkan lint untuk memastikan praktik kode yang baik
  flutter_lints: ^5.0.0

flutter:
  # Menggunakan material design icons
  uses-material-design: true

  # Menambahkan asset jika diperlukan
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Menambahkan font custom jika diperlukan
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
